#
# Module manifest for module 'PSGoogleAPI'
#
# Generated by: Kirill Zaslavskii <kirzas@gmail.com>
#
# Generated on: 24.01.2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\PSGoogleAPI.psm1'

# Version number of this module.
ModuleVersion = '0.0.2'

# ID used to uniquely identify this module
GUID = '6c493d2d-5c21-49bc-b94b-8ea006db691b'

# Author of this module
Author = 'kirzas'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2022 kirzas'

# Description of the functionality provided by this module
Description = 'PowerShell module for Google API'

# Minimum version of the Windows PowerShell engine required by this module
 PowerShellVersion = '5.0'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Get-GAPICalendar'
    'Get-GAPICalendarEvent'
    'Get-GAPIOAuthCode'
    'Get-GAPIOAuthToken'
    'Invoke-GAPIOAuthTokenRefresh'
    'Invoke-GAPIRestMethod'
    'New-GAPICalendarEvent'
    'Remove-GAPICalendarEvent'
    'Save-GAPIAccessToken'
    'Save-GAPIClientCredential'
    'Save-GAPIRefreshToken'
    # to be removed
    'Export-Credential'
    'Import-Credential'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/kirzas/PSGoogleAPI/blob/5a5acf9788d9e3fc4740b38ada2c74363e74421a/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/kirzas/PSGoogleAPI'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

